apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: laurareivinen-countries
  labels:
    app: laurareivinen-countries

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: laurareivinen-countries

  template:
    metadata:
      labels:
        app: laurareivinen-countries
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/laurareivinen-countries:master
          name: laurareivinen-countries
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        cloud.google.com/gke-nodepool: workshop-pool
