kind: Service
apiVersion: v1
metadata:
  labels:
    app: laurareivinen-countries
  name: laurareivinen-countries
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: laurareivinen-countries
